### ISSUE TITLE
Quote API intermittently uses Uniswap V2 pool with tiny liquidity instead of Balancer pool with good liquidity

### ISSUE THREAD

**Issue by enolan** [0xProject/0x-api#458]
Here's the request URL: `https://api.0x.org/swap/v1/quote?sellToken=0x44Ea84a85616F8e9cD719Fc843DE31D852ad7240&buyToken=0x3af375d9f77Ddd4F16F86A5D51a9386b7B4493Fa&sellAmount=1171000000000000000&excludedSources=MultiHop`. The specific amounts are irrelevant afaict. It's swapping nTRUMP tokens for yTRUMP tokens.

## Expected Behavior

So long as nothing has changed on chain, running the same HTTP request against the API should return the same result, and that result should give the best price available.

## Current Behavior

Some of the time the API returns a quote with a price of 0.000000000000002 that uses Uniswap v2, and some of the time it returns a quote with a price of 11.806856350190919 that uses Balancer. [Here](https://gist.github.com/enolan/2e54414161bdbf282c97ae00a5c44db3)'s examples of the JSON output.

## Steps to Reproduce (for bugs)

`curl 'https://api.0x.org/swap/v1/quote?sellToken=0x44Ea84a85616F8e9cD719Fc843DE31D852ad7240&buyToken=0x3af375d9f77Ddd4F16F86A5D51a9386b7B4493Fa&sellAmount=1171000000000000000&excludedSources=MultiHop'| jq .`

## Context

This shows up in https://catnip.exchange when trying to exit or enter positions.

**Comment by dekz** [comment]
@enolan thanks for reporting, sorry for the delay didn't see the notification.

This is due to the way we fetch Balancer pools (which is off-chain and performed on the first request). Only the second request has available pools. 

We have many API instances so this problem is exacerbated by load balancing across these many instances, and they can also cycle in an out. 

Will give some more thought on the best way to handle this, usually it is not a problem with popular tokens as they are constantly searched for.

**Comment by dekz** [comment]
This should now be fixed. If you see this behaviour again please reopen the issue.
